### ISSUE TITLE
Issue with Exp bar in unitframe

### ISSUE THREAD

**Issue by Aideenwolf** [p3lim-wow/oUF_Experience#10]
oUF 8.0.0
Exp 80000.24
oUF_Drk r30

Turning off the exp bar goes away turning it on gives the following error - not sure if this is oUF or the way the Exp bar is embedded.

8x ...Ons\oUF_Drk\embeds\oUF_Experience\oUF_Experience.lua:162: Usage: <unnamed>:SetAlpha(alpha 0 to 1)
[C]: in function `SetAlpha'
...Ons\oUF_Drk\embeds\oUF_Experience\oUF_Experience.lua:162: in function <...Ons\oUF_Drk\embeds\oUF_Experience\oUF_Experience.lua:150>
...Ons\oUF_Drk\embeds\oUF_Experience\oUF_Experience.lua:195: in function <...Ons\oUF_Drk\embeds\oUF_Experience\oUF_Experience.lua:182>
(tail call): ?
oUF\ouf-8.0.0.lua:211: in function <oUF\ouf.lua:200>
(tail call): ?
[C]: in function `Show'
FrameXML\SecureStateDriver.lua:83: in function <FrameXML\SecureStateDriver.lua:73>
FrameXML\SecureStateDriver.lua:137: in function <FrameXML\SecureStateDriver.lua:119>

Locals:
(*temporary) = <unnamed> {
 __owner = oUF_DrkPlayerFrame {
 }
 ForceUpdate = <function> defined @oUF_Drk\embeds\oUF_Experience\oUF_Experience.lua:205
 restedAlpha = 0.15
 __accountMaxLevel = 110
 Text = <unnamed> {
 }
 Rested = <unnamed> {
 }
 0 = <userdata>
}
(*temporary) = nil

**Comment by p3lim** [comment]
#9
